### ISSUE TITLE
issuer portal credentials list

### ISSUE THREAD

**Issue by severinstampler** [walt-id/waltid-issuer-portal#2]
The issuer portal, which is hosted here: https://issuer.waltid.org/ (type any email/password and hit the grey button), has currently  two checkboxes, for indicating which credential should be issued.

As we  also need to be able to input some data or "claims" (name/value fields), we would need other input options. I suggest that you:

1.) create selection box to define the type of credential
2.) show a different form (name/value) for each credential

**Comment by iietmoon** [comment]
@severinstampler  please can you explain more this task

**Comment by severinstampler** [comment]
In the issuer portal, the user should choose the type of Credential they want to get issued.
Additionally they can enter the credential data in a form, so that they get a customized credential, rather than one with all default values.

I made a quick UI which has checkboxes to select the type of credentials and a form with some values that one can fill for the credential data.
My idea was, that this form should support all the values of the credential subject, which depends on the type of credential.
For example a VerifiableId has these data fields:
firstName, lastName, dateOfBirth, currentAdress, gender, etc....

Maybe in a first step, you can check how to improve the layout of the existing form a little bit.

**Comment by iietmoon** [comment]
@severinstampler I pushed new design is minimalist and comfortable in eye, with input icons

**Comment by severinstampler** [comment]
Ok thanks. I will have a look tomorrow.
