### ISSUE TITLE
Design for Login Page (issuer-portal)

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-issuer-portal#3]
Instead of the current design, this template should be used: https://getbootstrap.com/docs/5.0/examples/sign-in/

**Comment by iietmoon** [comment]
is need to be centred inside the widget or full-screen?

**Comment by philpotisk** [comment]
in the issuer-portal, we don't have any widget. so plese center it, as in the template

**Comment by iietmoon** [comment]
Okay I got your idea

**Comment by iietmoon** [comment]
I pushed the new login design with the walitid logo and same as bootstrap example

**Comment by philpotisk** [comment]
@iietmoon the new login-desig is looking great!!
